# Generated by Django 2.2.4 on 2019-08-11 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tapp_up', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(default=None)),
                ('modified_date', models.DateTimeField(default=None)),
                ('quantity', models.IntegerField()),
                ('expense_date', models.DateTimeField()),
                ('good_type', models.CharField(max_length=126)),
                ('consumer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
