# Generated by Django 2.2.4 on 2019-08-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapp_up', '0004_auto_20190811_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(default=None)),
                ('modified_date', models.DateTimeField(default=None)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='expense',
            name='good_type',
        ),
        migrations.AddField(
            model_name='expense',
            name='good_type',
            field=models.ManyToManyField(to='tapp_up.Category'),
        ),
    ]
