# Generated by Django 2.2.4 on 2019-08-13 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tapp_up', '0005_auto_20190813_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='good_type',
        ),
        migrations.AddField(
            model_name='expense',
            name='good_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tapp_up.Category'),
        ),
    ]
