# Generated by Django 2.2.4 on 2019-08-13 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tapp_up', '0006_auto_20190813_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='consumer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='good_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='tapp_up.Category'),
            preserve_default=False,
        ),
    ]
