# Generated by Django 2.2.4 on 2019-08-17 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tapp_up', '0007_auto_20190813_1553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['expense_date']},
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='good_type',
            new_name='category',
        ),
    ]
